RBAC-ManagementStudio/src/main/java/se/esss/ics/rbac/jsf/permissions/DefinitionsRequestCacheBean.java
/*
 * Copyright (c) 2014 European Spallation Source
 * Copyright (c) 2014 Cosylab d.d.
 * 
 * This file is part of RBAC.
 * RBAC is free software: you can redistribute it and/or modify it under 
 * the terms of the GNU General Public License as published by the Free 
 * Software Foundation, either version 2 of the License, or any newer version.
 * 
 * This program is distributed in the hope that it will be useful, but WITHOUT
 * ANY WARRANTY; without even the implied warranty of MERCHANTABILITY or 
 * FITNESS FOR A PARTICULAR PURPOSE.  See the GNU General Public License for 
 * more details.
 * 
 * You should have received a copy of the GNU General Public License along with
 * this program. If not, see https://www.gnu.org/licenses/gpl-2.0.txt
 */
package se.esss.ics.rbac.jsf.permissions;

import java.io.Serializable;
import java.util.List;

import javax.ejb.EJB;
import javax.faces.bean.ManagedBean;
import javax.faces.bean.RequestScoped;

import se.esss.ics.rbac.datamodel.Permission;
import se.esss.ics.rbac.datamodel.Resource;
import se.esss.ics.rbac.datamodel.Role;
import se.esss.ics.rbac.datamodel.Rule;
import se.esss.ics.rbac.ejbs.interfaces.Permissions;
import se.esss.ics.rbac.ejbs.interfaces.Resources;
import se.esss.ics.rbac.ejbs.interfaces.Roles;
import se.esss.ics.rbac.ejbs.interfaces.Rules;

/**
 * <code>DefinitionsRequestCacheBean</code> is a request bean used on the definitions page. It provides access to DB
 * content by caching the results for the duration of the request. Using this bean eliminates multiple calls to the
 * database, which can be a result of primefaces requesting specific data multiple times.
 * 
 * @author <a href="mailto:miha.novak@cosylab.com">Miha Novak</a>
 */
@ManagedBean(name = "definitionsRequestCacheBean")
@RequestScoped
public class DefinitionsRequestCacheBean implements Serializable {

    private static final long serialVersionUID = 4421265100906853490L;
    @EJB
    private Permissions permissionsEJB;
    @EJB
    private Resources resourcesEJB;
    @EJB
    private Rules rulesEJB;
    @EJB
    private Roles rolesEJB;

    private int currentResourceId;

    private List<Permission> permissionsByResource;
    private List<Resource> resources;
    private List<Rule> rules;
    private List<Role> roles;

    /**
     * Retrieves list of permissions which corresponds to the selected resource from database and returns it.
     * Permissions are shown in permissions list on <code>/Permissions/Definitions</code> page.
     * 
     * @param resourceId resource id
     * @param refresh if true retrieve permissions from database, otherwise return cached permissions
     * 
     * @return permissions which corresponds to the selected resource.
     */
    public List<Permission> getPermissionsByResource(int resourceId, boolean refresh) {
        if (refresh || permissionsByResource == null || currentResourceId != resourceId) {
            currentResourceId = resourceId;
            permissionsByResource = permissionsEJB.getPermissionsByResource(resourceId);
        }
        return permissionsByResource;
    }

    /**
     * Retrieves list of resources from database and returns it. Resources are shown in resources drop down list on
     * <code>/Permissions/Definitions</code> page.
     * 
     * @return resources retrieved from database.
     */
    public List<Resource> getResources() {
        if (resources == null) {
            resources = resourcesEJB.getResources();
        }
        return resources;
    }

    /**
     * Retrieves list of rules from database and returns it. Rules are shown in drop down list on
     * <code>/Permissions/Definitions</code> page.
     * 
     * @return rules retrieved from database.
     */
    public List<Rule> getRules() {
        if (rules == null) {
            rules = rulesEJB.getRules();
        }
        return rules;
    }

    /**
     * @return roles which corresponds to the selected permission. Roles are shown in roles list box on
     *         <code>/Permissions/Definitions</code> page.
     */
    public List<Role> getRoles() {
        if (roles == null) {
            roles = rolesEJB.getRoles();
        }
        return roles;
    }
}

RBAC-ManagementStudio/src/main/java/se/esss/ics/rbac/jsf/permissions/IPGroupsBean.java
/*
 * Copyright (c) 2014 European Spallation Source
 * Copyright (c) 2014 Cosylab d.d.
 * 
 * This file is part of RBAC.
 * RBAC is free software: you can redistribute it and/or modify it under 
 * the terms of the GNU General Public License as published by the Free 
 * Software Foundation, either version 2 of the License, or any newer version.
 * 
 * This program is distributed in the hope that it will be useful, but WITHOUT
 * ANY WARRANTY; without even the implied warranty of MERCHANTABILITY or 
 * FITNESS FOR A PARTICULAR PURPOSE.  See the GNU General Public License for 
 * more details.
 * 
 * You should have received a copy of the GNU General Public License along with
 * this program. If not, see https://www.gnu.org/licenses/gpl-2.0.txt
 */
package se.esss.ics.rbac.jsf.permissions;

import java.io.Serializable;
import java.util.ArrayList;
import java.util.Collections;
import java.util.HashSet;
import java.util.List;
import java.util.Set;

import javax.ejb.EJB;
import javax.faces.bean.ManagedBean;
import javax.faces.bean.ManagedProperty;
import javax.faces.bean.ViewScoped;
import javax.inject.Inject;

import org.primefaces.context.RequestContext;
import org.primefaces.event.SelectEvent;
import org.primefaces.event.UnselectEvent;

import se.esss.ics.rbac.Util;
import se.esss.ics.rbac.datamodel.IPGroup;
import se.esss.ics.rbac.ejbs.interfaces.IPGroups;
import se.esss.ics.rbac.jsf.auth.LoginBean;
import se.esss.ics.rbac.jsf.auth.PermissionsBean;
import se.esss.ics.rbac.jsf.general.Constants;
import se.esss.ics.rbac.jsf.general.ManagementStudioExecutionTask;
import se.esss.ics.rbac.jsf.general.ManagementStudioTaskBean;
import se.esss.ics.rbac.jsf.general.Messages;

/**
 * <code>IPGroupsBean</code> is a managed bean (<code>ipGroupsBean</code>), which contains IP groups data and methods
 * for executing actions triggered on <code>/Permissions/IPGroups</code> page. IP groups bean is view scoped so it lives
 * as long as user interacting with IP groups page view.
 * 
 * @author <a href="mailto:miha.novak@cosylab.com">Miha Novak</a>
 */
@ManagedBean(name = "ipGroupsBean")
@ViewScoped
public class IPGroupsBean implements Serializable {

    private static final long serialVersionUID = -4606470694487210438L;

    @ManagedProperty(value = "#{loginBean}")
    private LoginBean loginBean;
    @ManagedProperty(value = "#{permissionsBean}")
    private PermissionsBean permissionsBean;
    @ManagedProperty(value = "#{taskBean}")
    private ManagementStudioTaskBean taskBean;
    @EJB
    private IPGroups ipGroupsEJB;
    @Inject
    private IPGroupsRequestCacheBean requestCacheBean;

    private String wildcard = Constants.ALL;
    private String newIpGroupName;
    private String newIpGroupDescription;
    private String updatedIpGroupName;
    private String updatedIpGroupDescription;
    private String ipGroupMember;
    private IPGroup selectedIPGroup;
    private String selectedMember;

    /**
     * Sets permissions bean which contains methods for determining permissions for specific actions for the logged in
     * user.
     * 
     * @param permissionsBean the permission bean through which the permissions can be checked
     */
    public void setPermissionsBean(PermissionsBean permissionsBean) {
        this.permissionsBean = permissionsBean;
    }

    /**
     * Sets login bean used for checking if a user is logged in.
     * 
     * @param loginBean the login bean through which the logged in user info can be retrieved
     */
    public void setLoginBean(LoginBean loginBean) {
        this.loginBean = loginBean;
    }

    /**
     * Sets management studio task bean used for executing tasks.
     * 
     * @param taskBean the management studio task bean
     */
    public void setTaskBean(ManagementStudioTaskBean taskBean) {
        this.taskBean = taskBean;
    }

    /**
     * Returns wildcard pattern which is used for searching by IP groups. Pattern is entered into search field on
     * <code>/Permissions/IPGroups</code> page.
     * 
     * @return wildcard pattern used for searching by IP groups.
     */
    public String getWildcard() {
        return wildcard;
    }

    /**
     * Sets wildcard pattern which is used for searching by IP groups. Pattern is entered into search field on
     * <code>/Permissions/IPGroups</code> page.
     * 
     * @param wildcard wildcard pattern used for searching by IP groups
     */
    public void setWildcard(String wildcard) {
        this.wildcard = wildcard;
    }

    /**
     * Returns IP group which is selected in IP groups list on <code>/Permissions/IPGroups</code> page.
     * 
     * @return selected IP group.
     */
    public IPGroup getSelectedIPGroup() {
        return selectedIPGroup;
    }

    /**
     * Sets IP group which is selected in IP groups list on <code>/Permissions/IPGroups</code> page.
     * 
     * @param selectedIPGroup selected IP group
     */
    public void setSelectedIPGroup(IPGroup selectedIPGroup) {
        if (selectedIPGroup != null && !selectedIPGroup.equals(this.selectedIPGroup)) {
            this.selectedIPGroup = selectedIPGroup;
            this.selectedMember = Constants.EMPTY_STRING;
        }
    }

    /**
     * Returns IP group member which is selected in members table on <code>/Permissions/IPGroups</code> page.
     * 
     * @return selected IP group member.
     */
    public String getSelectedMember() {
        return selectedMember;
    }

    /**
     * Sets IP group member which is selected in members table on <code>/Permissions/IPGroups</code> page.
     * 
     * @param selectedMember selected IP group member
     */
    public void setSelectedMember(String selectedMember) {
        this.selectedMember = selectedMember;
    }

    /**
     * Returns IP group member value which is entered into member field in add IP group member dialog on
     * <code>/Permissions/IPGroups</code> page.
     * 
     * @return IP group member entered into member field.
     */
    public String getIPGroupMember() {
        return ipGroupMember;
    }

    /**
     * Sets IP group member value which is entered into member field in add IP group member dialog on
     * <code>/Permissions/IPGroups</code> page.
     * 
     * @param ipGroupMember IP group member
     */
    public void setIPGroupMember(String ipGroupMember) {
        this.ipGroupMember = removeSpaces(ipGroupMember);
    }

    /**
     * @return selected IP group name which is shown in IP group name field on <code>/Permissions/IPGroups</code> page.
     */
    public String getIPGroupName() {
        if (isIPGroupSelected()) {
            return selectedIPGroup.getName();
        }
        return Constants.EMPTY_STRING;
    }

    /**
     * Returns new IP group name which is entered into IP group name field in add IP group dialog on
     * <code>/Permissions/IPGroups</code> page.
     * 
     * @return new IP group name which is entered into IP group name field.
     */
    public String getNewIPGroupName() {
        return newIpGroupName;
    }

    /**
     * Sets new IP group name which is entered into IP group name field in add IP group dialog on
     * <code>/Permissions/IPGroups</code> page.
     * 
     * @param newIpGroupName new IP group name
     */
    public void setNewIPGroupName(String newIpGroupName) {
        this.newIpGroupName = removeSpaces(newIpGroupName);
    }

    /**
     * Returns updated IP group name which is entered into IP group name field in edit IP group dialog on
     * <code>/Permissions/IPGroups</code> page.
     * 
     * @return updated IP group name which is entered into IP group name field.
     */
    public String getUpdatedIPGroupName() {
        return getIPGroupName();
    }

    /**
     * Sets updated IP group name which is entered into IP group name field in edit IP group dialog on
     * <code>/Permissions/IPGroups</code> page.
     * 
     * @param updatedIpGroupName updated IP group name
     */
    public void setUpdatedIPGroupName(String updatedIpGroupName) {
        this.updatedIpGroupName = removeSpaces(updatedIpGroupName);
    }

    /**
     * @return selected IP group description which is shown in IP group description field on
     *         <code>/Permissions/IPGroups</code> page.
     */
    public String getIPGroupDescription() {
        if (isIPGroupSelected()) {
            return selectedIPGroup.getDescription();
        }
        return Constants.EMPTY_STRING;
    }

    /**
     * Returns new IP group description which is entered into IP group description field in add IP group dialog on
     * <code>/Permissions/IPGroups</code> page.
     * 
     * @return new IP group description which is entered into IP group description field.
     */
    public String getNewIPGroupDescription() {
        return newIpGroupDescription;
    }

    /**
     * Sets new IP group description which is entered into IP group description field in add IP group dialog on
     * <code>/Permissions/IPGroups</code> page.
     * 
     * @param newIpGroupDescription new IP group description
     */
    public void setNewIPGroupDescription(String newIpGroupDescription) {
        this.newIpGroupDescription = newIpGroupDescription;
    }

    /**
     * Returns updated IP group description which is entered into IP group description field in edit IP group dialog on
     * <code>/Permissions/IPGroups</code> page.
     * 
     * @return updated IP group description which is entered into IP group description field.
     */
    public String getUpdatedIPGroupDescription() {
        return getIPGroupDescription();
    }

    /**
     * Sets updated IP group description which is entered into IP group description field in edit IP group dialog on
     * <code>/Permissions/IPGroups</code> page.
     * 
     * @param updatedIpGroupDescription updated IP group description
     */
    public void setUpdatedIPGroupDescription(String updatedIpGroupDescription) {
        this.updatedIpGroupDescription = updatedIpGroupDescription;
    }

    /**

RBAC-ManagementStudio/src/main/java/se/esss/ics/rbac/jsf/permissions/IPGroupsRequestCacheBean.java
/*
 * Copyright (c) 2014 European Spallation Source
 * Copyright (c) 2014 Cosylab d.d.
 * 
 * This file is part of RBAC.
 * RBAC is free software: you can redistribute it and/or modify it under 
 * the terms of the GNU General Public License as published by the Free 
 * Software Foundation, either version 2 of the License, or any newer version.
 * 
 * This program is distributed in the hope that it will be useful, but WITHOUT
 * ANY WARRANTY; without even the implied warranty of MERCHANTABILITY or 
 * FITNESS FOR A PARTICULAR PURPOSE.  See the GNU General Public License for 
 * more details.
 * 
 * You should have received a copy of the GNU General Public License along with
 * this program. If not, see https://www.gnu.org/licenses/gpl-2.0.txt
 */
package se.esss.ics.rbac.jsf.permissions;

import java.io.Serializable;
import java.util.List;

import javax.ejb.EJB;
import javax.faces.bean.ManagedBean;
import javax.faces.bean.RequestScoped;

import se.esss.ics.rbac.datamodel.IPGroup;
import se.esss.ics.rbac.ejbs.interfaces.IPGroups;
import se.esss.ics.rbac.jsf.general.Constants;

/**
 * <code>IPGroupsRequestCacheBean</code> is a request bean used on the ip groups page. It provides access to DB content
 * by caching the results for the duration of the request. Using this bean eliminates multiple calls to the database,
 * which can be a result of primefaces requesting specific data multiple times.
 * 
 * @author <a href="mailto:miha.novak@cosylab.com">Miha Novak</a>
 */
@ManagedBean(name = "ipGroupsRequestCacheBean")
@RequestScoped
public class IPGroupsRequestCacheBean implements Serializable {

    private static final long serialVersionUID = -8024739239221453582L;

    @EJB
    private IPGroups ipGroupsEJB;

    private String currentWildcard = Constants.ALL_DB;

    private List<IPGroup> ipGroups;
    private List<IPGroup> ipGroupsWildcard;

    /**
     * Retrieves list of IP groups from database and returns it. IP groups are shown in IP groups list on
     * <code>/Permissions/IPGroups</code> page.
     * 
     * @param refresh if true retrieves ip groups from database otherwise return cached ip groups
     * 
     * @return list of IP groups retrieved from database.
     */
    public List<IPGroup> getIPGroups(boolean refresh) {
        if (refresh || ipGroups == null) {
            ipGroups = ipGroupsEJB.getIPGroups();
        }
        return ipGroups;
    }

    /**
     * Retrieves list of IP groups (which matches wildcard) from database and returns it. IP groups are shown in IP
     * groups list on <code>/Permissions/IPGroups</code> page.
     * 
     * @param wildcard search ip groups by wildcard
     * @param refresh if true retrieves ip groups from database otherwise return cached ip groups
     * 
     * @return list of IP groups retrieved from database.
     */
    public List<IPGroup> getIPGroupsByWildcard(String wildcard, boolean refresh) {
        if (refresh || ipGroupsWildcard == null || !currentWildcard.equals(wildcard)) {
            currentWildcard = wildcard;
            ipGroupsWildcard = ipGroupsEJB.getIPGroupsByWildcard(wildcard);
        }
        return ipGroupsWildcard;
    }
}

RBAC-ManagementStudio/src/main/webapp/permissions/dialogs/add-expression.xhtml
<ui:composition xmlns:ui="http://java.sun.com/jsf/facelets"
    xmlns:f="http://java.sun.com/jsf/core"
    xmlns:h="http://java.sun.com/jsf/html"
    xmlns:p="http://primefaces.org/ui">
    <h:form id="addExpressionForm">
        <p:panelGrid styleClass="noBorderPanelgrid">
            <p:row>
                <p:column>
                    <p:outputLabel value="Name:" />
                </p:column>
                <p:column>
                    <p:inputText value="#{expressionsBean.newExpressionLongName}"
                        required="true" requiredMessage="Name is required."
                        styleClass="inputFields"/>
                </p:column>
            </p:row>
            <p:row>
                <p:column>
                    <p:outputLabel value="Short Name:" />
                </p:column>
                <p:column>
                    <p:inputText label="Short Name" value="#{expressionsBean.newExpressionName}"
                        required="true" requiredMessage="Short Name is required."
                        styleClass="inputFields" >
                        <f:validateLength minimum="1" maximum="10"/>
                    </p:inputText>
                </p:column>
            </p:row>
            <p:row>
                <p:column styleClass="columnTopAlignment">
                    <p:outputLabel value="Description:" />
                </p:column>
                <p:column styleClass="columnTopAlignment">
                    <p:inputTextarea
                        label="Description" value="#{expressionsBean.newExpressionDescription}" rows="8"
                        styleClass="inputFields" autoResize="false" scrollHeight="150" >
                        <f:validateLength maximum="1000"/>
                    </p:inputTextarea>
                </p:column>
            </p:row>
            <p:row>
                <p:column>
                    <p:outputLabel value="Definition:" />
                </p:column>
                <p:column>
                    <p:inputText label="Definition" value="#{expressionsBean.newExpressionDefinition}"
                        required="true" requiredMessage="Definition field is required."
                        styleClass="inputFields" >
                        <f:validateLength maximum="1000"/>
                    </p:inputText>
                </p:column>
            </p:row>
            <p:row>
                <p:column colspan="2">
                    <h:panelGroup layout="block" styleClass="rightCommandButtonPanel">
                        <p:commandButton value="OK" styleClass="commandButton"
                            action="#{expressionsBean.createExpression}"
                            oncomplete="if(!args.validationFailed) PF('addExpressionDialog').hide()"
                            update="addExpressionForm :expressionsForm:expressionsListPanelGrid :expressionsForm:propertiesPanelGrid :siteContainerGrowl :editExpressionForm" />
                        <p:commandButton value="Cancel" immediate="true"
                            onclick="PF('addExpressionDialog').hide()"
                            update="addExpressionForm" styleClass="commandButton">
                            <p:resetInput target=":addExpressionDialog" />
                        </p:commandButton>
                    </h:panelGroup>
                </p:column>
            </p:row>
        </p:panelGrid>
    </h:form>
</ui:composition>

RBAC-ManagementStudio/src/main/webapp/permissions/dialogs/add-ipgroup-member.xhtml
<ui:composition xmlns:ui="http://java.sun.com/jsf/facelets"
    xmlns:f="http://java.sun.com/jsf/core"
    xmlns:h="http://java.sun.com/jsf/html"
    xmlns:p="http://primefaces.org/ui">
    <h:form id="addIPGroupMemberForm">
        <p:panelGrid styleClass="noBorderPanelgrid">
            <p:row>
                <p:column>
                    <p:outputLabel value="Member:" />
                </p:column>
                <p:column>
                    <p:inputText value="#{ipGroupsBean.IPGroupMember}" required="true"
                        requiredMessage="Name field is required." styleClass="inputFields" />
                </p:column>
            </p:row>
            <p:row>
                <p:column colspan="2">
                    <h:panelGroup layout="block" styleClass="rightCommandButtonPanel">
                        <p:commandButton value="OK" styleClass="commandButton"
                            action="#{ipGroupsBean.createIPGroupMember}"
                            oncomplete="if(!args.validationFailed) PF('addIPGroupMemberDialog').hide()"
                            update="addIPGroupMemberForm :ipGroupsForm:propertiesPanelGrid :siteContainerGrowl" />
                        <p:commandButton value="Cancel" immediate="true"
                            update="addIPGroupMemberForm"
                            onclick="PF('addIPGroupMemberDialog').hide()"
                            styleClass="commandButton">
                            <p:resetInput target=":addIPGroupMemberDialog" />
                        </p:commandButton>
                    </h:panelGroup>
                </p:column>
            </p:row>
        </p:panelGrid>
    </h:form>
</ui:composition>

RBAC-ManagementStudio/src/main/webapp/permissions/dialogs/add-ipgroup.xhtml
<ui:composition xmlns:ui="http://java.sun.com/jsf/facelets"
    xmlns:f="http://java.sun.com/jsf/core"
    xmlns:h="http://java.sun.com/jsf/html"
    xmlns:p="http://primefaces.org/ui">
    <h:form id="addIPGroupForm">
        <p:panelGrid styleClass="noBorderPanelgrid">
            <p:row>
                <p:column>
                    <p:outputLabel value="Name:" />
                </p:column>
                <p:column>
                    <p:inputText value="#{ipGroupsBean.newIPGroupName}" required="true"
                        requiredMessage="Name field is required." styleClass="inputFields" />
                </p:column>
            </p:row>
            <p:row>
                <p:column styleClass="columnTopAlignment">
                    <p:outputLabel value="Description:" />
                </p:column>
                <p:column styleClass="columnTopAlignment">
                    <p:inputTextarea value="#{ipGroupsBean.newIPGroupDescription}"
                        rows="8" styleClass="inputFields" autoResize="false"
                        scrollHeight="150" />
                </p:column>
            </p:row>
            <p:row>
                <p:column colspan="2">
                    <h:panelGroup layout="block" styleClass="rightCommandButtonPanel">
                        <p:commandButton value="OK" styleClass="commandButton"
                            action="#{ipGroupsBean.createIPGroup}"
                            oncomplete="if(!args.validationFailed) PF('addIPGroupDialog').hide()"
                            update="addIPGroupForm :ipGroupsForm :siteContainerGrowl :editIPGroupForm" />
                        <p:commandButton value="Cancel" immediate="true"
                            update="addIPGroupForm" onclick="PF('addIPGroupDialog').hide()"
                            styleClass="commandButton">
                            <p:resetInput target=":addIPGroupDialog" />
                        </p:commandButton>
                    </h:panelGroup>
                </p:column>
            </p:row>
        </p:panelGrid>
    </h:form>
</ui:composition>

RBAC-ManagementStudio/src/main/webapp/permissions/dialogs/add-rule.xhtml
<ui:composition xmlns:ui="http://java.sun.com/jsf/facelets"
    xmlns:f="http://java.sun.com/jsf/core"
    xmlns:h="http://java.sun.com/jsf/html"
    xmlns:p="http://primefaces.org/ui">
    <h:form id="addRuleForm">
        <p:panelGrid styleClass="noBorderPanelgrid">
            <p:row>
                <p:column>
                    <p:outputLabel value="Name:" />
                </p:column>
                <p:column>
                    <p:inputText value="#{rulesBean.newRuleName}" required="true"
                        requiredMessage="Name is required." styleClass="inputFields" />
                </p:column>
            </p:row>
            <p:row>
                <p:column styleClass="columnTopAlignment">
                    <p:outputLabel value="Description:" />
                </p:column>
                <p:column styleClass="columnTopAlignment">
                    <p:inputTextarea label="Description" value="#{rulesBean.newRuleDescription}" rows="8"
                        styleClass="inputFields" autoResize="false" scrollHeight="150" >
                        <f:validateLength maximum="1000"/>
                    </p:inputTextarea>
                </p:column>
            </p:row>
            <p:row>
                <p:column>
                    <p:outputLabel value="Definition:" />
                </p:column>
                <p:column>
                    <p:inputText label="Definition" value="#{rulesBean.newRuleDefinition}"
                        styleClass="inputFields" >
                        <f:validateLength maximum="1000"/>
                    </p:inputText>
                </p:column>
            </p:row>
            <p:row>
                <p:column colspan="2">
                    <h:panelGroup layout="block" styleClass="rightCommandButtonPanel">
                        <p:commandButton value="OK" styleClass="commandButton"
                            action="#{rulesBean.createRule}"
                            oncomplete="if(!args.validationFailed) PF('addRuleDialog').hide()"
                            update="addRuleForm :rulesForm :siteContainerGrowl :editRuleForm" />
                        <p:commandButton value="Cancel" immediate="true"
                            update="addRuleForm" onclick="PF('addRuleDialog').hide()"
                            styleClass="commandButton">
                            <p:resetInput target=":addRuleDialog" />
                        </p:commandButton>
                    </h:panelGroup>
                </p:column>
            </p:row>
        </p:panelGrid>
    </h:form>
</ui:composition>

RBAC-ManagementStudio/src/main/webapp/permissions/dialogs/edit-ipgroup.xhtml
<ui:composition xmlns:ui="http://java.sun.com/jsf/facelets"
    xmlns:f="http://java.sun.com/jsf/core"
    xmlns:h="http://java.sun.com/jsf/html"
    xmlns:p="http://primefaces.org/ui">
    <h:form id="editIPGroupForm">
        <p:panelGrid styleClass="noBorderPanelgrid">
            <p:row>
                <p:column>
                    <p:outputLabel value="Name:" />
                </p:column>
                <p:column>
                    <p:inputText value="#{ipGroupsBean.updatedIPGroupName}" required="true"
                        requiredMessage="Name field is required." styleClass="inputFields" />
                </p:column>
            </p:row>
            <p:row>
                <p:column styleClass="columnTopAlignment">
                    <p:outputLabel value="Description:" />
                </p:column>
                <p:column styleClass="columnTopAlignment">
                    <p:inputTextarea value="#{ipGroupsBean.updatedIPGroupDescription}"
                        rows="8" styleClass="inputFields" autoResize="false"
                        scrollHeight="150" />
                </p:column>
            </p:row>
            <p:row>
                <p:column colspan="2">
                    <h:panelGroup layout="block" styleClass="rightCommandButtonPanel">
                        <p:commandButton value="OK" styleClass="commandButton"
                            action="#{ipGroupsBean.updateIPGroup}"
                            oncomplete="if(!args.validationFailed) PF('editIPGroupDialog').hide()"
                            update="editIPGroupForm :ipGroupsForm :siteContainerGrowl" />
                        <p:commandButton value="Cancel" immediate="true"
                            update="editIPGroupForm" onclick="PF('editIPGroupDialog').hide()"
                            styleClass="commandButton">
                            <p:resetInput target=":editIPGroupDialog" />
                        </p:commandButton>
                    </h:panelGroup>
                </p:column>
            </p:row>
        </p:panelGrid>
    </h:form>
</ui:composition>