RBAC-ManagementStudio/src/main/java/se/esss/ics/rbac/jsf/permissions/DefinitionsBean.java
/*
 * Copyright (c) 2014 European Spallation Source
 * Copyright (c) 2014 Cosylab d.d.
 *
 * This file is part of RBAC.
 * RBAC is free software: you can redistribute it and/or modify it under
 * the terms of the GNU General Public License as published by the Free
 * Software Foundation, either version 2 of the License, or any newer version.
 *
 * This program is distributed in the hope that it will be useful, but WITHOUT
 * ANY WARRANTY; without even the implied warranty of MERCHANTABILITY or
 * FITNESS FOR A PARTICULAR PURPOSE.  See the GNU General Public License for
 * more details.
 *
 * You should have received a copy of the GNU General Public License along with
 * this program. If not, see https://www.gnu.org/licenses/gpl-2.0.txt
 */
package se.esss.ics.rbac.jsf.permissions;

import java.io.BufferedReader;
import java.io.ByteArrayInputStream;
import java.io.ByteArrayOutputStream;
import java.io.IOException;
import java.io.InputStream;
import java.io.InputStreamReader;
import java.io.Serializable;
import java.nio.charset.Charset;
import java.text.SimpleDateFormat;
import java.util.ArrayList;
import java.util.Date;
import java.util.Iterator;
import java.util.List;
import java.util.TimeZone;
import java.util.concurrent.TimeUnit;

import javax.annotation.PostConstruct;
import javax.ejb.EJB;
import javax.faces.application.FacesMessage;
import javax.faces.bean.ManagedBean;
import javax.faces.bean.ManagedProperty;
import javax.faces.bean.ViewScoped;
import javax.faces.context.FacesContext;
import javax.inject.Inject;

import org.apache.poi.ss.usermodel.Row;
import org.apache.poi.xssf.usermodel.XSSFSheet;
import org.apache.poi.xssf.usermodel.XSSFWorkbook;
import org.primefaces.context.RequestContext;
import org.primefaces.event.FileUploadEvent;
import org.primefaces.model.DefaultStreamedContent;
import org.primefaces.model.StreamedContent;
import org.primefaces.model.UploadedFile;
import org.slf4j.Logger;
import org.slf4j.LoggerFactory;

import se.esss.ics.rbac.Util;
import se.esss.ics.rbac.datamodel.ExclusiveAccess;
import se.esss.ics.rbac.datamodel.Permission;
import se.esss.ics.rbac.datamodel.Resource;
import se.esss.ics.rbac.datamodel.Role;
import se.esss.ics.rbac.datamodel.Rule;
import se.esss.ics.rbac.ejbs.interfaces.Admin;
import se.esss.ics.rbac.ejbs.interfaces.ManagementStudioLogs;
import se.esss.ics.rbac.ejbs.interfaces.Permissions;
import se.esss.ics.rbac.ejbs.interfaces.Roles;
import se.esss.ics.rbac.jsf.auth.LoginBean;
import se.esss.ics.rbac.jsf.auth.PermissionsBean;
import se.esss.ics.rbac.jsf.general.Constants;
import se.esss.ics.rbac.jsf.general.ManagementStudioExecutionTask;
import se.esss.ics.rbac.jsf.general.ManagementStudioTaskBean;
import se.esss.ics.rbac.jsf.general.Messages;
import se.esss.ics.rbac.jsf.utils.Wildcard;

/**
 * <code>DefinitionsBean</code> is a managed bean (<code>permissionsDefinitionBean</code>), which contains permissions
 * data and methods for executing actions triggered on <code>/Permissions/Definitions</code> page. Definitions bean is
 * view scoped so it lives as long as user interacting with definitions page view.
 *
 * @author <a href="mailto:miha.novak@cosylab.com">Miha Novak</a>
 */
@ManagedBean(name = "permissionsDefinitionBean")
@ViewScoped
public class DefinitionsBean implements Serializable {

    private static final long serialVersionUID = -4657224036935545840L;
    private static final transient Logger LOGGER = LoggerFactory.getLogger(DefinitionsBean.class);
    private static final Charset CHARSET = Charset.forName("UTF-8");
    private static final String NO_DESCRIPTION = "<No Description>";

    @ManagedProperty(value = "#{permissionsBean}")
    private PermissionsBean permissionsBean;
    @ManagedProperty(value = "#{loginBean}")
    private LoginBean loginBean;
    @ManagedProperty(value = "#{taskBean}")
    private ManagementStudioTaskBean taskBean;
    @EJB
    private Admin adminEJB;
    @EJB
    private Permissions permissionsEJB;
    @EJB
    private Roles rolesEJB;
    @EJB
    private ManagementStudioLogs managementStudioLogEJB;
    @Inject
    private DefinitionsRequestCacheBean requestCacheBean;

    private String wildcard = Constants.ALL;
    private String newPermissionName;
    private String newPermissionDescription;
    private String updatedPermissionName;
    private String updatedPermissionDescription;
    private Boolean exclusiveAccessAllowed;
    private Resource selectedResource;
    private Permission selectedPermission;
    private Rule selectedRule;
    private Role selectedRole;
    private Date exclusiveAccessDuration;
    private List<Permission> permissions;

    // roles
    private List<Role> rolesSourceList;
    private List<Role> selectedRolesSourceList;
    private List<Role> rolesTargetList;
    private List<Role> selectedRolesTargetList;

    /**
     * Sets default exclusive access duration value. Value is retrieved from database. Method is called post construct.
     */
    @PostConstruct
    private void initialize() {
        rolesSourceList = new ArrayList<Role>();
        rolesTargetList = new ArrayList<Role>();
        resetExclusiveAccessDuration();
    }

    /**
     * Sets permissions bean which contains methods for determining permissions for specific actions for the logged in
     * user.
     *
     * @param permissionsBean the permissions bean through which permission can be checked
     */
    public void setPermissionsBean(PermissionsBean permissionsBean) {
        this.permissionsBean = permissionsBean;
    }

    /**
     * Sets login bean used for checking if a user is logged in.
     *
     * @param loginBean the login bean through which the logged in user info can be retrieved
     */
    public void setLoginBean(LoginBean loginBean) {
        this.loginBean = loginBean;
    }

    /**
     * Sets management studio task bean used for executing tasks.
     *
     * @param taskBean the management studio task bean
     */
    public void setTaskBean(ManagementStudioTaskBean taskBean) {
        this.taskBean = taskBean;
    }

    /**
     * Sets wildcard pattern which is used for searching by permissions. Pattern is entered into search field on
     * <code>/Permissions/Definitions</code> page.
     *
     * @param wildcard wildcard pattern
     */
    public void setWildcard(String wildcard) {
        this.wildcard = wildcard;
    }

    /**
     * @return wildcard pattern which is used for searching by permissions. Pattern is entered into search field on
     *         <code>/Permissions/Definitions</code> page.
     */
    public String getWildcard() {
        return wildcard;
    }

    /**
     * @return resource which is selected in drop down list <code>/Permissions/Definitions</code> page.
     */
    public Resource getSelectedResource() {
        return selectedResource;
    }

    /**
     * Sets resource which is selected in drop down list on <code>/Permissions/Definitions</code> page.
     *
     * @param selectedResource selected resource
     */
    public void setSelectedResource(Resource selectedResource) {
        this.selectedResource = selectedResource;
        selectedPermission = null;
        selectedRole = null;
        selectedRule = null;
    }

    /**
     * @return permission which is selected in list box on <code>/Permissions/Definitions</code> page.
     */
    public Permission getSelectedPermission() {
        return selectedPermission;
    }

    /**
     * Sets permission which is selected in list box on <code>/Permissions/Definitions</code> page.
     *
     * @param selectedPermission selected permission
     */
    public void setSelectedPermission(Permission selectedPermission) {
        this.selectedPermission = selectedPermission;
        selectedRole = null;
        selectedRule = null;
    }

    /**
     * @return rule which is selected in drop down list on <code>/Permissions/Definitions</code> page.
     */
    public Rule getSelectedRule() {
        if (isPermissionSelected()) {
            selectedRule = selectedPermission.getRule();
        }
        return selectedRule;
    }

    /**
     * Sets rule which is selected on <code>/Permissions/Definitions</code> page.
     *
     * @param selectedRule selected rule
     */
    public void setSelectedRule(Rule selectedRule) {
        this.selectedRule = selectedRule;
    }

    /**
     * @return role which is selected in roles list on <code>/Permissions/Definitions</code> page.
     */
    public Role getSelectedRole() {
        return selectedRole;
    }

    /**
     * Sets role which is selected in roles list on <code>/Permissions/Definitions</code> page.
     *
     * @param selectedRole selected role
     */
    public void setSelectedRole(Role selectedRole) {
        this.selectedRole = selectedRole;
    }

    /**
     * @return selected permission name which is shown in permission name field on <code>/Permissions/Definitions</code>
     *         page.
     */
    public String getPermissionName() {
        if (isPermissionSelected()) {
            return selectedPermission.getName();
        }
        return Constants.EMPTY_STRING;
    }

    /**
     * Returns new permission name which is entered into permission name field in add new permission dialog on
     * <code>/Permissions/Definitions</code> page.
     *
     * @return new permission name which is entered into permission name field.
     */
    public String getNewPermissionName() {
        return newPermissionName;
    }

    /**
     * Sets new permission name which is entered into permission name field in add new permission dialog on
     * <code>/Permissions/Definitions</code> page.
     *
     * @param newPermissionName new permission name
     */
    public void setNewPermissionName(String newPermissionName) {
        this.newPermissionName = removeSpaces(newPermissionName);
    }

    /**
     * Returns updated permission name which is entered into permission name field in edit permission dialog on

RBAC-ManagementStudio/src/main/java/se/esss/ics/rbac/jsf/permissions/DefinitionsRequestCacheBean.java
/*
 * Copyright (c) 2014 European Spallation Source
 * Copyright (c) 2014 Cosylab d.d.
 * 
 * This file is part of RBAC.
 * RBAC is free software: you can redistribute it and/or modify it under 
 * the terms of the GNU General Public License as published by the Free 
 * Software Foundation, either version 2 of the License, or any newer version.
 * 
 * This program is distributed in the hope that it will be useful, but WITHOUT
 * ANY WARRANTY; without even the implied warranty of MERCHANTABILITY or 
 * FITNESS FOR A PARTICULAR PURPOSE.  See the GNU General Public License for 
 * more details.
 * 
 * You should have received a copy of the GNU General Public License along with
 * this program. If not, see https://www.gnu.org/licenses/gpl-2.0.txt
 */
package se.esss.ics.rbac.jsf.permissions;

import java.io.Serializable;
import java.util.List;

import javax.ejb.EJB;
import javax.faces.bean.ManagedBean;
import javax.faces.bean.RequestScoped;

import se.esss.ics.rbac.datamodel.Permission;
import se.esss.ics.rbac.datamodel.Resource;
import se.esss.ics.rbac.datamodel.Role;
import se.esss.ics.rbac.datamodel.Rule;
import se.esss.ics.rbac.ejbs.interfaces.Permissions;
import se.esss.ics.rbac.ejbs.interfaces.Resources;
import se.esss.ics.rbac.ejbs.interfaces.Roles;
import se.esss.ics.rbac.ejbs.interfaces.Rules;

/**
 * <code>DefinitionsRequestCacheBean</code> is a request bean used on the definitions page. It provides access to DB
 * content by caching the results for the duration of the request. Using this bean eliminates multiple calls to the
 * database, which can be a result of primefaces requesting specific data multiple times.
 * 
 * @author <a href="mailto:miha.novak@cosylab.com">Miha Novak</a>
 */
@ManagedBean(name = "definitionsRequestCacheBean")
@RequestScoped
public class DefinitionsRequestCacheBean implements Serializable {

    private static final long serialVersionUID = 4421265100906853490L;
    @EJB
    private Permissions permissionsEJB;
    @EJB
    private Resources resourcesEJB;
    @EJB
    private Rules rulesEJB;
    @EJB
    private Roles rolesEJB;

    private int currentResourceId;

    private List<Permission> permissionsByResource;
    private List<Resource> resources;
    private List<Rule> rules;
    private List<Role> roles;

    /**
     * Retrieves list of permissions which corresponds to the selected resource from database and returns it.
     * Permissions are shown in permissions list on <code>/Permissions/Definitions</code> page.
     * 
     * @param resourceId resource id
     * @param refresh if true retrieve permissions from database, otherwise return cached permissions
     * 
     * @return permissions which corresponds to the selected resource.
     */
    public List<Permission> getPermissionsByResource(int resourceId, boolean refresh) {
        if (refresh || permissionsByResource == null || currentResourceId != resourceId) {
            currentResourceId = resourceId;
            permissionsByResource = permissionsEJB.getPermissionsByResource(resourceId);
        }
        return permissionsByResource;
    }

    /**
     * Retrieves list of resources from database and returns it. Resources are shown in resources drop down list on
     * <code>/Permissions/Definitions</code> page.
     * 
     * @return resources retrieved from database.
     */
    public List<Resource> getResources() {
        if (resources == null) {
            resources = resourcesEJB.getResources();
        }
        return resources;
    }

    /**
     * Retrieves list of rules from database and returns it. Rules are shown in drop down list on
     * <code>/Permissions/Definitions</code> page.
     * 
     * @return rules retrieved from database.
     */
    public List<Rule> getRules() {
        if (rules == null) {
            rules = rulesEJB.getRules();
        }
        return rules;
    }

    /**
     * @return roles which corresponds to the selected permission. Roles are shown in roles list box on
     *         <code>/Permissions/Definitions</code> page.
     */
    public List<Role> getRoles() {
        if (roles == null) {
            roles = rolesEJB.getRoles();
        }
        return roles;
    }
}

RBAC-ManagementStudio/src/main/java/se/esss/ics/rbac/jsf/permissions/IPGroupsRequestCacheBean.java
/*
 * Copyright (c) 2014 European Spallation Source
 * Copyright (c) 2014 Cosylab d.d.
 * 
 * This file is part of RBAC.
 * RBAC is free software: you can redistribute it and/or modify it under 
 * the terms of the GNU General Public License as published by the Free 
 * Software Foundation, either version 2 of the License, or any newer version.
 * 
 * This program is distributed in the hope that it will be useful, but WITHOUT
 * ANY WARRANTY; without even the implied warranty of MERCHANTABILITY or 
 * FITNESS FOR A PARTICULAR PURPOSE.  See the GNU General Public License for 
 * more details.
 * 
 * You should have received a copy of the GNU General Public License along with
 * this program. If not, see https://www.gnu.org/licenses/gpl-2.0.txt
 */
package se.esss.ics.rbac.jsf.permissions;

import java.io.Serializable;
import java.util.List;

import javax.ejb.EJB;
import javax.faces.bean.ManagedBean;
import javax.faces.bean.RequestScoped;

import se.esss.ics.rbac.datamodel.IPGroup;
import se.esss.ics.rbac.ejbs.interfaces.IPGroups;
import se.esss.ics.rbac.jsf.general.Constants;

/**
 * <code>IPGroupsRequestCacheBean</code> is a request bean used on the ip groups page. It provides access to DB content
 * by caching the results for the duration of the request. Using this bean eliminates multiple calls to the database,
 * which can be a result of primefaces requesting specific data multiple times.
 * 
 * @author <a href="mailto:miha.novak@cosylab.com">Miha Novak</a>
 */
@ManagedBean(name = "ipGroupsRequestCacheBean")
@RequestScoped
public class IPGroupsRequestCacheBean implements Serializable {

    private static final long serialVersionUID = -8024739239221453582L;

    @EJB
    private IPGroups ipGroupsEJB;

    private String currentWildcard = Constants.ALL_DB;

    private List<IPGroup> ipGroups;
    private List<IPGroup> ipGroupsWildcard;

    /**
     * Retrieves list of IP groups from database and returns it. IP groups are shown in IP groups list on
     * <code>/Permissions/IPGroups</code> page.
     * 
     * @param refresh if true retrieves ip groups from database otherwise return cached ip groups
     * 
     * @return list of IP groups retrieved from database.
     */
    public List<IPGroup> getIPGroups(boolean refresh) {
        if (refresh || ipGroups == null) {
            ipGroups = ipGroupsEJB.getIPGroups();
        }
        return ipGroups;
    }

    /**
     * Retrieves list of IP groups (which matches wildcard) from database and returns it. IP groups are shown in IP
     * groups list on <code>/Permissions/IPGroups</code> page.
     * 
     * @param wildcard search ip groups by wildcard
     * @param refresh if true retrieves ip groups from database otherwise return cached ip groups
     * 
     * @return list of IP groups retrieved from database.
     */
    public List<IPGroup> getIPGroupsByWildcard(String wildcard, boolean refresh) {
        if (refresh || ipGroupsWildcard == null || !currentWildcard.equals(wildcard)) {
            currentWildcard = wildcard;
            ipGroupsWildcard = ipGroupsEJB.getIPGroupsByWildcard(wildcard);
        }
        return ipGroupsWildcard;
    }
}

RBAC-ManagementStudio/src/main/webapp/users/permissions.xhtml
<ui:composition template="../templates/site.xhtml"
    xmlns:ui="http://java.sun.com/jsf/facelets"
    xmlns:f="http://java.sun.com/jsf/core"
    xmlns:h="http://java.sun.com/jsf/html"
    xmlns:p="http://primefaces.org/ui">

    <ui:define name="title">RBAC Management Studio: User Permissions</ui:define>

    <ui:define name="content">
        <h:form id="userPermissionsForm">
            <p:panelGrid id="userPermissionsPanelGrid"
                styleClass="noBorderPanelgrid">
                <p:row>
                    <p:column styleClass="withoutPadding">
                        <p:panelGrid id="users" styleClass="noBorderPanelgrid">
                            <p:row>
                                <p:column>
                                    <p:inputText id="searchInput" value="#{userInfoBean.wildcard}"
                                        styleClass="inputFields">
                                        <p:ajax event="keyup" process="searchInput"
                                            partialSubmit="true" update="usersListBox usersPermissions" />
                                    </p:inputText>
                                </p:column>
                            </p:row>
                            <p:row>
                                <p:column>
                                    <p:selectOneListbox id="usersListBox"
                                        converter="#{userConverter}"
                                        value="#{userInfoBean.selectedUser}" styleClass="mainListBox">
                                        <f:selectItems value="#{userInfoBean.usersList}" var="user"
                                            itemLabel="#{user.lastName} #{user.firstName}"
                                            itemValue="#{user}" />
                                        <p:ajax event="change"
                                            listener="#{userInfoBean.releaseSelection}"
                                            update="usersPermissions" />
                                    </p:selectOneListbox>
                                </p:column>
                            </p:row>
                            <p:row>
                                <p:column>
                                    <h:panelGroup layout="block"
                                        styleClass="centerCommandButtonPanel">
                                        <p:commandButton id="loadUsersButton" update="usersListBox"
                                            value="Load users" action="#{usersBean.loadUsers}"
                                            styleClass="commandButtonLarge" />
                                    </h:panelGroup>
                                </p:column>
                            </p:row>
                        </p:panelGrid>
                    </p:column>
                    <p:column styleClass="withoutPadding columnTopAlignment">
                        <p:panelGrid id="usersPermissions" styleClass="noBorderPanelgrid">
                            <p:row>
                                <p:column>
                                    <h2>
                                        <p:outputLabel
                                            value="All permissions of the user #{userInfoBean.selectedUser.firstName} #{userInfoBean.selectedUser.lastName}" />
                                    </h2>
                                </p:column>
                            </p:row>
                            <p:row>
                                <p:column>
                                    <p:dataTable id="userPermissionsTable" var="role"
                                        value="#{usersRequestCacheBean.userPermissions}" style="width:843px"
                                        styleClass="rolesPermissionTable" scrollable="true"
                                        scrollHeight="570">
                                        <p:column headerText="Permission">
                                            <h:outputText value="#{role.permissionName}" />
                                        </p:column>
                                        <p:column headerText="Resource">
                                            <h:outputText value="#{role.resourceName}" />
                                        </p:column>
                                        <p:column headerText="Role">
                                            <h:outputText value="#{role.roleName}" />
                                        </p:column>
                                        <f:facet name="footer">
                                            <div></div>
                                        </f:facet>
                                    </p:dataTable>
                                </p:column>
                            </p:row>
                        </p:panelGrid>
                    </p:column>
                </p:row>
            </p:panelGrid>
            <p:blockUI block="userPermissionsPanelGrid"
                trigger="loadUsersButton, loadUsersRemoteCommand">
                <p:graphicImage library="images" name="ajax-loader.gif" />
                <br />
                Loading data ... 
            </p:blockUI>
            <p:remoteCommand id="loadUsersRemoteCommand" name="lazyload"
                update="usersListBox" autoRun="true">
                <f:setPropertyActionListener value="#{true}"
                    target="#{usersBean.areUsersLoaded}" />
            </p:remoteCommand>
             <script type="text/javascript">
                $(document).ready(function() {
                	updateUserPermissionsListbox();
                });
				function updateUserPermissionsListbox() {
                    $("#userPermissionsForm\\:usersListBox .ui-selectlistbox-listcontainer").css("height", "600px");
				}
            </script>
			<p:outputPanel autoUpdate="true">
			    <h:outputScript id="applyChangeHandler">
			        updateUserPermissionsListbox();
			    </h:outputScript>
			</p:outputPanel>          
        </h:form>
    </ui:define>
</ui:composition>