RBAC-ManagementStudio/src/main/java/se/esss/ics/rbac/jsf/permissions/DefinitionsRequestCacheBean.java
/*
 * Copyright (c) 2014 European Spallation Source
 * Copyright (c) 2014 Cosylab d.d.
 * 
 * This file is part of RBAC.
 * RBAC is free software: you can redistribute it and/or modify it under 
 * the terms of the GNU General Public License as published by the Free 
 * Software Foundation, either version 2 of the License, or any newer version.
 * 
 * This program is distributed in the hope that it will be useful, but WITHOUT
 * ANY WARRANTY; without even the implied warranty of MERCHANTABILITY or 
 * FITNESS FOR A PARTICULAR PURPOSE.  See the GNU General Public License for 
 * more details.
 * 
 * You should have received a copy of the GNU General Public License along with
 * this program. If not, see https://www.gnu.org/licenses/gpl-2.0.txt
 */
package se.esss.ics.rbac.jsf.permissions;

import java.io.Serializable;
import java.util.List;

import javax.ejb.EJB;
import javax.faces.bean.ManagedBean;
import javax.faces.bean.RequestScoped;

import se.esss.ics.rbac.datamodel.Permission;
import se.esss.ics.rbac.datamodel.Resource;
import se.esss.ics.rbac.datamodel.Role;
import se.esss.ics.rbac.datamodel.Rule;
import se.esss.ics.rbac.ejbs.interfaces.Permissions;
import se.esss.ics.rbac.ejbs.interfaces.Resources;
import se.esss.ics.rbac.ejbs.interfaces.Roles;
import se.esss.ics.rbac.ejbs.interfaces.Rules;

/**
 * <code>DefinitionsRequestCacheBean</code> is a request bean used on the definitions page. It provides access to DB
 * content by caching the results for the duration of the request. Using this bean eliminates multiple calls to the
 * database, which can be a result of primefaces requesting specific data multiple times.
 * 
 * @author <a href="mailto:miha.novak@cosylab.com">Miha Novak</a>
 */
@ManagedBean(name = "definitionsRequestCacheBean")
@RequestScoped
public class DefinitionsRequestCacheBean implements Serializable {

    private static final long serialVersionUID = 4421265100906853490L;
    @EJB
    private Permissions permissionsEJB;
    @EJB
    private Resources resourcesEJB;
    @EJB
    private Rules rulesEJB;
    @EJB
    private Roles rolesEJB;

    private int currentResourceId;

    private List<Permission> permissionsByResource;
    private List<Resource> resources;
    private List<Rule> rules;
    private List<Role> roles;

    /**
     * Retrieves list of permissions which corresponds to the selected resource from database and returns it.
     * Permissions are shown in permissions list on <code>/Permissions/Definitions</code> page.
     * 
     * @param resourceId resource id
     * @param refresh if true retrieve permissions from database, otherwise return cached permissions
     * 
     * @return permissions which corresponds to the selected resource.
     */
    public List<Permission> getPermissionsByResource(int resourceId, boolean refresh) {
        if (refresh || permissionsByResource == null || currentResourceId != resourceId) {
            currentResourceId = resourceId;
            permissionsByResource = permissionsEJB.getPermissionsByResource(resourceId);
        }
        return permissionsByResource;
    }

    /**
     * Retrieves list of resources from database and returns it. Resources are shown in resources drop down list on
     * <code>/Permissions/Definitions</code> page.
     * 
     * @return resources retrieved from database.
     */
    public List<Resource> getResources() {
        if (resources == null) {
            resources = resourcesEJB.getResources();
        }
        return resources;
    }

    /**
     * Retrieves list of rules from database and returns it. Rules are shown in drop down list on
     * <code>/Permissions/Definitions</code> page.
     * 
     * @return rules retrieved from database.
     */
    public List<Rule> getRules() {
        if (rules == null) {
            rules = rulesEJB.getRules();
        }
        return rules;
    }

    /**
     * @return roles which corresponds to the selected permission. Roles are shown in roles list box on
     *         <code>/Permissions/Definitions</code> page.
     */
    public List<Role> getRoles() {
        if (roles == null) {
            roles = rolesEJB.getRoles();
        }
        return roles;
    }
}

RBAC-ManagementStudio/src/main/java/se/esss/ics/rbac/jsf/permissions/ExpressionsBean.java
/*
 * Copyright (c) 2014 European Spallation Source
 * Copyright (c) 2014 Cosylab d.d.
 * 
 * This file is part of RBAC.
 * RBAC is free software: you can redistribute it and/or modify it under 
 * the terms of the GNU General Public License as published by the Free 
 * Software Foundation, either version 2 of the License, or any newer version.
 * 
 * This program is distributed in the hope that it will be useful, but WITHOUT
 * ANY WARRANTY; without even the implied warranty of MERCHANTABILITY or 
 * FITNESS FOR A PARTICULAR PURPOSE.  See the GNU General Public License for 
 * more details.
 * 
 * You should have received a copy of the GNU General Public License along with
 * this program. If not, see https://www.gnu.org/licenses/gpl-2.0.txt
 */
package se.esss.ics.rbac.jsf.permissions;

import java.io.Serializable;
import java.util.ArrayList;
import java.util.List;

import javax.ejb.EJB;
import javax.faces.bean.ManagedBean;
import javax.faces.bean.ManagedProperty;
import javax.faces.bean.ViewScoped;
import javax.inject.Inject;

import org.primefaces.context.RequestContext;

import se.esss.ics.rbac.Util;
import se.esss.ics.rbac.datamodel.Expression;
import se.esss.ics.rbac.datamodel.Rule;
import se.esss.ics.rbac.ejbs.interfaces.Expressions;
import se.esss.ics.rbac.ejbs.interfaces.Rules;
import se.esss.ics.rbac.jsf.auth.LoginBean;
import se.esss.ics.rbac.jsf.auth.PermissionsBean;
import se.esss.ics.rbac.jsf.general.Constants;
import se.esss.ics.rbac.jsf.general.ManagementStudioExecutionTask;
import se.esss.ics.rbac.jsf.general.ManagementStudioTaskBean;
import se.esss.ics.rbac.jsf.general.Messages;

/**
 * <code>ExpressionsBean</code> is a managed bean (<code>expressionsBean</code>), which contains expressions data and
 * methods for executing actions triggered on <code>/Permissions/Expressions</code> page. Expressions bean is view
 * scoped so it lives as long as user interacting with expressions page view.
 * 
 * @author <a href="mailto:miha.novak@cosylab.com">Miha Novak</a>
 */
@ManagedBean(name = "expressionsBean")
@ViewScoped
public class ExpressionsBean implements Serializable {

    private static final long serialVersionUID = -3357182350048618525L;

    @ManagedProperty(value = "#{loginBean}")
    private LoginBean loginBean;
    @ManagedProperty(value = "#{permissionsBean}")
    private PermissionsBean permissionsBean;
    @ManagedProperty(value = "#{taskBean}")
    private ManagementStudioTaskBean taskBean;
    @EJB
    private Expressions expressionsEJB;
    @EJB
    private Rules rulesEJB;
    @Inject
    private ExpressionsRequestCacheBean requestCacheBean;
    
    private String wildcard = Constants.ALL;
    private String newExpressionName;
    private String newExpressionLongName;
    private String newExpressionDescription;
    private String newExpressionDefinition;
    private String updatedExpressionName;
    private String updatedExpressionLongName;
    private String updatedExpressionDescription;
    private String updatedExpressionDefinition;
    private Expression selectedExpression;
    private List<Rule> expressionRules;

    /**
     * Sets permissions bean which contains methods for determining permissions for specific actions for the logged in
     * user.
     * 
     * @param permissionsBean the permission bean through which the permissions can be checked
     */
    public void setPermissionsBean(PermissionsBean permissionsBean) {
        this.permissionsBean = permissionsBean;
    }

    /**
     * Sets login bean used for checking if a user is logged in.
     * 
     * @param loginBean the login bean through which the logged in user info can be retrieved
     */
    public void setLoginBean(LoginBean loginBean) {
        this.loginBean = loginBean;
    }

    /**
     * Sets management studio task bean used for executing tasks.
     * 
     * @param taskBean the management studio task bean
     */
    public void setTaskBean(ManagementStudioTaskBean taskBean) {
        this.taskBean = taskBean;
    }

    /**
     * Returns wildcard pattern which is used for searching by expressions. Pattern is entered into search field on
     * <code>/Permissions/Expressions</code> page.
     * 
     * @return wildcard pattern used for searching by expressions.
     */
    public String getWildcard() {
        return wildcard;
    }

    /**
     * Sets wildcard pattern which is used for searching by expressions. Pattern is entered into search field on
     * <code>/Permissions/Expressions</code> page.
     * 
     * @param wildcard wildcard pattern used for searching by expressions
     */
    public void setWildcard(String wildcard) {
        this.wildcard = wildcard;
    }

    /**
     * Returns expression which is selected in expressions list on <code>/Permissions/Expressions</code> page.
     * 
     * @return selected expression.
     */
    public Expression getSelectedExpression() {
        return selectedExpression;
    }

    /**
     * Sets expression which is selected in expressions list on <code>/Permissions/Expressions</code> page.
     * 
     * @param selectedExpression selected expression
     */
    public void setSelectedExpression(Expression selectedExpression) {
        this.selectedExpression = selectedExpression;
    }

    /**
     * @return selected expression name which is shown in expression name field on <code>/Permissions/Expressions</code>
     *         page.
     */
    public String getExpressionName() {
        if (selectedExpression != null) {
            return selectedExpression.getName();
        }
        return Constants.EMPTY_STRING;
    }

    /**
     * Returns new expression name which is entered into expression name field in add expression dialog on
     * <code>/Permissions/Expressions</code> page.
     * 
     * @return new expression name which is entered into expression name field.
     */
    public String getNewExpressionName() {
        return newExpressionName;
    }

    /**
     * Sets new expression name which is entered into expression name field in add expression dialog on
     * <code>/Permissions/Expressions</code> page.
     * 
     * @param newExpressionName new expression name
     */
    public void setNewExpressionName(String newExpressionName) {
        this.newExpressionName = newExpressionName;
    }

    /**
     * Returns updated expression name which is entered into expression name field in edit expression dialog on
     * <code>/Permissions/Expressions</code> page.
     * 
     * @return updated expression name which is entered into expression name field.
     */
    public String getUpdatedExpressionName() {
        return getExpressionName();
    }

    /**
     * Sets updated expression name which is entered into expression name field in edit expression dialog on
     * <code>/Permissions/Expressions</code> page.
     * 
     * @param updatedExpressionName updated expression name
     */
    public void setUpdatedExpressionName(String updatedExpressionName) {
        this.updatedExpressionName = updatedExpressionName;
    }

    /**
     * @return selected expression long name which is shown in expression long name field on
     *         <code>/Permissions/Expressions</code> page.
     */
    public String getExpressionLongName() {
        if (selectedExpression != null) {
            return selectedExpression.getLongName();
        }
        return Constants.EMPTY_STRING;
    }

    /**
     * Returns new expression long name which is entered into expression long name field in add expression dialog on
     * <code>/Permissions/Expressions</code> page.
     * 
     * @return new expression long name which is entered into expression long name field.
     */
    public String getNewExpressionLongName() {
        return newExpressionLongName;
    }

    /**
     * Sets new expression long name which is entered into expression long name field in add expression dialog on
     * <code>/Permissions/Expressions</code> page.
     * 
     * @param newExpressionLongName new expression long name
     */
    public void setNewExpressionLongName(String newExpressionLongName) {
        this.newExpressionLongName = newExpressionLongName;
    }

    /**
     * Returns updated expression long name which is entered into expression long name field in edit expression dialog
     * on <code>/Permissions/Expressions</code> page.
     * 
     * @return updated expression long name which is entered into expression long name field.
     */
    public String getUpdatedExpressionLongName() {
        return getExpressionLongName();
    }

    /**
     * Sets updated expression long name which is entered into expression long name field in edit expression dialog on
     * <code>/Permissions/Expressions</code> page.
     * 
     * @param updatedExpressionLongName updated expression long name
     */
    public void setUpdatedExpressionLongName(String updatedExpressionLongName) {
        this.updatedExpressionLongName = updatedExpressionLongName;
    }

    /**
     * @return selected expression description which is shown in expression description field on
     *         <code>/Permissions/Expressions</code> page.
     */
    public String getExpressionDescription() {
        if (selectedExpression != null) {
            return selectedExpression.getDescription();
        }
        return Constants.EMPTY_STRING;
    }

    /**
     * Returns new expression description which is entered into expression description field in add expression dialog on
     * <code>/Permissions/Expressions</code> page.
     * 
     * @return new expression description which is entered into expression description field.
     */
    public String getNewExpressionDescription() {
        return newExpressionDescription;
    }

    /**
     * Sets new expression description which is entered into expression description field in add expression dialog on
     * <code>/Permissions/Expressions</code> p age.
     * 
     * @param newExpressionDescription new expression description

RBAC-ManagementStudio/src/main/java/se/esss/ics/rbac/jsf/permissions/IPGroupsRequestCacheBean.java
/*
 * Copyright (c) 2014 European Spallation Source
 * Copyright (c) 2014 Cosylab d.d.
 * 
 * This file is part of RBAC.
 * RBAC is free software: you can redistribute it and/or modify it under 
 * the terms of the GNU General Public License as published by the Free 
 * Software Foundation, either version 2 of the License, or any newer version.
 * 
 * This program is distributed in the hope that it will be useful, but WITHOUT
 * ANY WARRANTY; without even the implied warranty of MERCHANTABILITY or 
 * FITNESS FOR A PARTICULAR PURPOSE.  See the GNU General Public License for 
 * more details.
 * 
 * You should have received a copy of the GNU General Public License along with
 * this program. If not, see https://www.gnu.org/licenses/gpl-2.0.txt
 */
package se.esss.ics.rbac.jsf.permissions;

import java.io.Serializable;
import java.util.List;

import javax.ejb.EJB;
import javax.faces.bean.ManagedBean;
import javax.faces.bean.RequestScoped;

import se.esss.ics.rbac.datamodel.IPGroup;
import se.esss.ics.rbac.ejbs.interfaces.IPGroups;
import se.esss.ics.rbac.jsf.general.Constants;

/**
 * <code>IPGroupsRequestCacheBean</code> is a request bean used on the ip groups page. It provides access to DB content
 * by caching the results for the duration of the request. Using this bean eliminates multiple calls to the database,
 * which can be a result of primefaces requesting specific data multiple times.
 * 
 * @author <a href="mailto:miha.novak@cosylab.com">Miha Novak</a>
 */
@ManagedBean(name = "ipGroupsRequestCacheBean")
@RequestScoped
public class IPGroupsRequestCacheBean implements Serializable {

    private static final long serialVersionUID = -8024739239221453582L;

    @EJB
    private IPGroups ipGroupsEJB;

    private String currentWildcard = Constants.ALL_DB;

    private List<IPGroup> ipGroups;
    private List<IPGroup> ipGroupsWildcard;

    /**
     * Retrieves list of IP groups from database and returns it. IP groups are shown in IP groups list on
     * <code>/Permissions/IPGroups</code> page.
     * 
     * @param refresh if true retrieves ip groups from database otherwise return cached ip groups
     * 
     * @return list of IP groups retrieved from database.
     */
    public List<IPGroup> getIPGroups(boolean refresh) {
        if (refresh || ipGroups == null) {
            ipGroups = ipGroupsEJB.getIPGroups();
        }
        return ipGroups;
    }

    /**
     * Retrieves list of IP groups (which matches wildcard) from database and returns it. IP groups are shown in IP
     * groups list on <code>/Permissions/IPGroups</code> page.
     * 
     * @param wildcard search ip groups by wildcard
     * @param refresh if true retrieves ip groups from database otherwise return cached ip groups
     * 
     * @return list of IP groups retrieved from database.
     */
    public List<IPGroup> getIPGroupsByWildcard(String wildcard, boolean refresh) {
        if (refresh || ipGroupsWildcard == null || !currentWildcard.equals(wildcard)) {
            currentWildcard = wildcard;
            ipGroupsWildcard = ipGroupsEJB.getIPGroupsByWildcard(wildcard);
        }
        return ipGroupsWildcard;
    }
}

RBAC-ManagementStudio/src/main/webapp/permissions/expressions.xhtml
<ui:composition template="../templates/site.xhtml"
    xmlns:ui="http://java.sun.com/jsf/facelets"
    xmlns:f="http://java.sun.com/jsf/core"
    xmlns:h="http://java.sun.com/jsf/html"
    xmlns:p="http://primefaces.org/ui"
    xmlns:pe="http://primefaces.org/ui/extensions">

    <ui:define name="title">RBAC Management Studio: Expressions</ui:define>

    <ui:define name="content">
        <h:form id="expressionsForm">
            <p:panelGrid id="expressionsPanelGrid" styleClass="noBorderPanelgrid">
                <p:row>
                    <p:column styleClass="withoutPadding">
                        <p:panelGrid id="expressionsListPanelGrid"
                            styleClass="noBorderPanelgrid">
                            <p:row>
                                <p:column>
                                    <p:inputText id="searchInput"
                                        value="#{expressionsBean.wildcard}" style="width: 280px">
                                        <p:ajax event="keyup" process="searchInput"
                                            partialSubmit="true" update="expressionsListBox expressionsListButtons propertiesPanelGrid" />
                                    </p:inputText>
                                </p:column>
                            </p:row>
                            <p:row>
                                <p:column>
                                    <p:selectOneListbox id="expressionsListBox"
                                        converter="#{expressionConverter}"
                                        value="#{expressionsBean.selectedExpression}"
                                        style="width:283px; height: 600px">
                                        <f:selectItems value="#{expressionsBean.expressions}"
                                            var="expression" itemLabel="#{expression.longName}"
                                            itemValue="#{expression}" />
                                        <p:ajax event="change"
                                            update="propertiesPanelGrid expressionsListButtons" />
                                    </p:selectOneListbox>
                                </p:column>
                            </p:row>
                            <p:row>
                                <p:column>
                                    <h:panelGroup layout="block" id="expressionsListButtons"
                                        styleClass="centerCommandButtonPanel">
                                        <p:commandButton value="Add" styleClass="commandButton"
                                            disabled="#{!permissionsBean.canManageRule(true)}"
                                            action="#{expressionsBean.showAddExpressionDialog()}" />
                                        <p:commandButton value="Remove" styleClass="commandButton"
                                            action="#{expressionsBean.removeExpression}"
                                            update="expressionsForm :siteContainerGrowl"
                                            disabled="#{expressionsBean.removeExpressionButtonDisabled
                                                || !permissionsBean.canManageRule(true)}">
                                            <p:confirm header="Confirmation"
                                                message="Do you really want to remove selected expression?"
                                                icon="ui-icon-help" />
                                        </p:commandButton>
                                    </h:panelGroup>
                                </p:column>
                            </p:row>
                        </p:panelGrid>
                    </p:column>
                    <p:column styleClass="withoutPadding columnTopAlignment">
                        <p:row>
                            <p:panelGrid id="propertiesPanelGrid" styleClass="noBorderPanelgrid" style="margin-top:2px;">
                                <p:row>
                                    <p:column colspan="2">
                                        <h2>
                                            <p:outputLabel
                                                value="Selected Expression:" />
                                        </h2>
                                    </p:column>
                                </p:row>
                                <p:row>
                                    <p:column>
                                        <p:outputLabel value="Name:" />
                                    </p:column>
                                    <p:column>
                                        <p:inputText value="#{expressionsBean.expressionName}"
                                            readonly="true" style="width: 280px" />
                                    </p:column>
                                </p:row>
                                <p:row>
                                    <p:column>
                                        <p:outputLabel value="Long Name:" />
                                    </p:column>
                                    <p:column>
                                        <p:inputText value="#{expressionsBean.expressionLongName}"
                                            readonly="true" style="width: 280px" />
                                    </p:column>
                                </p:row>
                                <p:row>
                                    <p:column styleClass="columnTopAlignmentText">
                                        <p:outputLabel value="Description:" />
                                    </p:column>
                                    <p:column>
                                        <p:inputTextarea
                                            value="#{expressionsBean.expressionDescription}" rows="6"
                                            readonly="true" style="width:280px; height:122px"
                                            scrollHeight="330" autoResize="false" />
                                    </p:column>
                                </p:row>
                                <p:row>
                                    <p:column colspan="2">
                                        <h:panelGroup layout="block" style="padding-right: 270px"
                                            styleClass="centerCommandButtonPanel">
                                            <p:commandButton value="Edit Expression Info"
                                                styleClass="commandButtonLarge"
                                                action="#{expressionsBean.showEditExpressionDialog()}"
                                                disabled="#{expressionsBean.editExpressionInfoButtonDisabled
                                                    || !permissionsBean.canManageRule(true)}" />
                                        </h:panelGroup>
                                    </p:column>
                                </p:row>
                                <p:row>
                                    <p:column>
                                        <p:outputLabel value="Definition:" />
                                    </p:column>
                                    <p:column>
                                        <p:inputText value="#{expressionsBean.expressionDefinition}"
                                            readonly="true" style="width: 651px" />
                                    </p:column>
                                </p:row>
                                <p:row>
                                    <p:column colspan="2">
                                        <h2>
                                            <p:outputLabel value="Rules" />
                                        </h2>
                                    </p:column>
                                </p:row>
                                <p:row>
                                    <p:column colspan="2" styleClass="columnTopAlignment">
                                        <p:dataTable var="rule" value="#{expressionsBean.rules}"
                                            scrollable="true" scrollHeight="250"
                                            styleClass="rolesPermissionTable" style="width:760px">
                                            <p:column headerText="Rules">
                                                <h:outputText value="#{rule.definition}" />
                                            </p:column>
                                            <f:facet name="footer">
                                                <div></div>
                                            </f:facet>
                                        </p:dataTable>
                                    </p:column>
                                </p:row>
                            </p:panelGrid>
                        </p:row>
                    </p:column>
                </p:row>
            </p:panelGrid>
            <script type="text/javascript">
                $(document).ready(function() {
                	updateExpressionsListbox();
                });
				function updateExpressionsListbox() {
                    $("#expressionsForm\\:expressionsListBox .ui-selectlistbox-listcontainer").css("height", "600px");
				}
            </script>
			<p:outputPanel autoUpdate="true">
			    <h:outputScript id="applyChangeHandler">
			        updateExpressionsListbox();
			    </h:outputScript>
			</p:outputPanel> 
        </h:form>
        <p:dialog header="Add Expression" closable="false" modal="true" dynamic="true" 
            resizable="false" showEffect="fade" hideEffect="fade"
            id="addExpressionDialog" widgetVar="addExpressionDialog">
            <ui:include src="dialogs/add-expression.xhtml" />
        </p:dialog>
        <p:dialog header="Edit Expression" closable="false" modal="true" dynamic="true" 
            resizable="false" showEffect="fade" hideEffect="fade"
            id="editExpressionDialog" widgetVar="editExpressionDialog">
            <ui:include src="dialogs/edit-expression.xhtml" />
        </p:dialog>
    </ui:define>
</ui:composition>